### ISSUE TITLE
Question about reducing integration time

### ISSUE THREAD

**Issue by dhevang** [gudrunhe/secdec#18]
Hi, I am trying to compute multi-loop integrals, which are very computationally expensive and was wondering if someone has some suggestions on how to evaluate them efficiently.

I have 1-, 2- and 3-loop diagrams that I would like to evaluate.
The 3-loop one is impractical to evaluate directly.
On the other hand, my problem involves low-momentum particles which makes an Eikonal approximation a viable possibility to reduce complexity.
In this approximation, a massive propagator with p^2=1 and k the momenta of a soft photon, reduces as:
[(p+k)^2 - 1]^-1 --> [2 * p * k]^-1

My 1-loop integral represents a triangle Feynman diagram with 1 photon exchanged between two charged massive particles (p1^2 = p2^2 = 1): 
loop_momenta = ['k1'],
external_momenta = ['p1','p2'],
propagators = ['k1**2','(p1 - k1)**2 - 1','(p2 + k1)**2 - 1'],
powerlist = [1, 1, 1],

The direct evaluation works fine (and quickly) with pysecdec and I would like to use this to test the Eikonal approximation.

The Eikonal version of this integral would be:
propagators = ['k1**2', '-2 * p1 * k1', '2 * p2 * k1']
Using decomposition_method='iterative', split=True or False, I get results with 100% errors.
This issue was explained in issue #4 as being caused by poles that are not at the end-points of integration and not contour deformed either.
A "manual" method to evaluate that integral by splitting the integral into 2 parts and changing variables was proposed.
However, I wonder if there exists such a simple manual method for my 2- and 3-loop diagrams as well.  

My 2-loop integral is:
propagators = ['k1** 2' , 'k2** 2' , '(p1 - k1)**2 - 1', '(p2 + k1)**2 - 1', '(p1 - k1 - k2)**2 - 1', '(p2 + k1 + k2)**2 - 1'],
This takes about 10 hours of GPU time to get sufficiently small stat errors (QMC integration method).

My 3-loop integral is:
propagators = ['k1** 2','k2** 2','k3**2', '(p1 - k1)**2 - 1', '(p2 + k1)**2 - 1', '(p1 - k1 - k2)**2 - 1', '(p2 + k1 + k2)**2 - 1', '(p1 - k1 - k2 - k3)**2 - 1', '(p2 + k1 + k2 + k3)**2 - 1']
Trying to evaluate this directly results in 328 sectors.
Given the amount of time needed for the 2-loop case, I dare not try integrating this directly...
I hope that after implementing the Eikonal approximation here, the integration time would be greatly reduced but the above issue gets in the way.

I am using pysecdec version 1.5.2 and evaluating the integrals with a Nvidia Quadro RTX5000 GPU.

Thanks for any help on how to proceed!

**Comment by dhevang** [comment]
I should also add that the long GPU times that I mentioned seem to be mainly caused by the kinematic region of interest to me, which is near the mass threshold: p1*p2 ~> 1.0.  Also, I have about 20 bins of p1*p2 to compute (all near the mass threshold).

**Comment by j-schlenk** [comment]
I don't think it is possible to approximate the integral close to threshold using the eikonal limit since k is the loop momentum and therefore k^2 << 2* p*k is not valid in all parts of loop momentum space.
After applying the eikonal approximation, the one loop integral you are trying to calculate is scaleless and should be set to zero in dimensional regularisation (this is why the integration is not converging).

To find a valid approximation of the integral close to threshold one can use expansion by regions. Unfortunately the pySecDec implementation of expansion by regions does not support threshold expansions of this type yet. To get around this limitation you could try to apply a splitting as proposed in [1206.0546](https://arxiv.org/abs/1206.0546) and described in issue #4 before expanding.

**Comment by dhevang** [comment]
Ok, thanks for the feedback!
