### ISSUE TITLE
python version flag

### ISSUE THREAD

**Issue by ChristophDl** [gudrunhe/secdec#5]
Hi,

I am trying to install pySecDec through the tarball, but I cannot get it to use the correct version of python.

My system has multiple python versions installed and in particular, "$ python" points to a version without numpy.
However, other versions have both sympy and numpy installed, e.g. the one reachable through "$ python3".

Is there a flag or global variable that I can set to declare the path to the correct version of python?

Please let me know if this is not possible, then I'll try to reach out to my system admin.

Thanks!

**Comment by magv** [comment]
You can set the `PYTHON` environment variable to the name of your python interpreter (i.e. `python3`), and it will be used during the building of the integration libraries.

You could in principle also install numpy & sympy yourself with `python -m pip install --user "numpy>=1.6" "sympy>=0.7.6,!=1.7"`, this does not require administrator privileges. There is no need though.

(Note that we plan to drop Python 2 compatibility in the future and always use `python3`).

**Comment by ChristophDl** [comment]
Thanks for the quick reply!
Setting PYTHON=python3 resolved the issue with numpy.

However, now I get errors related to Vegas and Cuba. Please see the attached file.

[pySecInstall.txt](https://github.com/gudrunhe/secdec/files/6829297/pySecInstall.txt)

**Comment by magv** [comment]
Yeah, Cuba tries to build its Mathematica libraries, which we don't need at all, and then fails for whatever reason (broken Mathematica installation?). To disable this, you could patch Cuba's `configure` and replace `mcc` with `/bin/false`, which is what we'll do in the next release, or temporary `ln -s /bin/false ~/.local/bin/mcc` (assuming `~/.local/bin` is in your `PATH`). In both cases Cuba should detect that `mcc` fails, and skip building the Mathematica extensions.

Anyway, you should probably use QMC instead of Cuba/Vegas, it's better for pretty much all integrals, and *much* better on some.

**Comment by ChristophDl** [comment]
I created `~/.local/bin`, added it to my `PATH` and created the mentioned symbolic link. Now `make` finished successfully and the examples also run without problems.
Thanks again!
